# Generated by Django 4.1.1 on 2022-11-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniqueuser',
            name='userFriends',
        ),
        migrations.AddField(
            model_name='uniqueuser',
            name='userFriends',
            field=models.ManyToManyField(blank=True, to='louslist.uniqueuser'),
        ),
    ]
