# Generated by Django 4.1.1 on 2022-12-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0003_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueuser',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
