# Generated by Django 4.1.1 on 2022-12-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0005_uniqueuser_is_authenticate_uniqueuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueuser',
            name='Major',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='uniqueuser',
            name='Year',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='uniqueuser',
            name='firstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='uniqueuser',
            name='lastName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
